// All-time college football greats — dataset for the 15-0 draft game.
// Fields: n = name, s = school, p = position, e = era, r = rating (0-99).
// Positions: QB RB WR TE | EDGE DT LB CB S  (FLEX draws from RB/WR/TE)
// Ratings: 96-99 = inner-circle legend / Heisman; 90-95 = all-time great;
//          84-89 = star / 1st-rounder; 78-83 = very good starter.
// v1 — high-confidence players only. Expandable.

export const PLAYERS = [
  // ===== ALABAMA =====
  { n: "Tua Tagovailoa", s: "Alabama", p: "QB", e: "2010s", r: 91 },
  { n: "Bryce Young", s: "Alabama", p: "QB", e: "2020s", r: 90 },
  { n: "Mac Jones", s: "Alabama", p: "QB", e: "2020s", r: 84 },
  { n: "Derrick Henry", s: "Alabama", p: "RB", e: "2010s", r: 95 },
  { n: "Mark Ingram", s: "Alabama", p: "RB", e: "2010s", r: 90 },
  { n: "Najee Harris", s: "Alabama", p: "RB", e: "2020s", r: 88 },
  { n: "Julio Jones", s: "Alabama", p: "WR", e: "2010s", r: 94 },
  { n: "Amari Cooper", s: "Alabama", p: "WR", e: "2010s", r: 93 },
  { n: "DeVonta Smith", s: "Alabama", p: "WR", e: "2020s", r: 94 },
  { n: "Jaylen Waddle", s: "Alabama", p: "WR", e: "2020s", r: 89 },
  { n: "O.J. Howard", s: "Alabama", p: "TE", e: "2010s", r: 86 },
  { n: "Will Anderson Jr.", s: "Alabama", p: "EDGE", e: "2020s", r: 95 },
  { n: "Derrick Thomas", s: "Alabama", p: "EDGE", e: "1980s", r: 96 },
  { n: "Jonathan Allen", s: "Alabama", p: "DT", e: "2010s", r: 90 },
  { n: "Quinnen Williams", s: "Alabama", p: "DT", e: "2010s", r: 90 },
  { n: "C.J. Mosley", s: "Alabama", p: "LB", e: "2010s", r: 89 },
  { n: "Reuben Foster", s: "Alabama", p: "LB", e: "2010s", r: 86 },
  { n: "Patrick Surtain II", s: "Alabama", p: "CB", e: "2020s", r: 90 },
  { n: "Marlon Humphrey", s: "Alabama", p: "CB", e: "2010s", r: 86 },
  { n: "Minkah Fitzpatrick", s: "Alabama", p: "S", e: "2010s", r: 91 },
  { n: "Mark Barron", s: "Alabama", p: "S", e: "2010s", r: 85 },

  // ===== OHIO STATE =====
  { n: "Troy Smith", s: "Ohio State", p: "QB", e: "2000s", r: 89 },
  { n: "Justin Fields", s: "Ohio State", p: "QB", e: "2020s", r: 90 },
  { n: "C.J. Stroud", s: "Ohio State", p: "QB", e: "2020s", r: 89 },
  { n: "Dwayne Haskins", s: "Ohio State", p: "QB", e: "2010s", r: 85 },
  { n: "Archie Griffin", s: "Ohio State", p: "RB", e: "1970s", r: 97 },
  { n: "Eddie George", s: "Ohio State", p: "RB", e: "1990s", r: 93 },
  { n: "Ezekiel Elliott", s: "Ohio State", p: "RB", e: "2010s", r: 92 },
  { n: "Cris Carter", s: "Ohio State", p: "WR", e: "1980s", r: 91 },
  { n: "Marvin Harrison Jr.", s: "Ohio State", p: "WR", e: "2020s", r: 93 },
  { n: "Garrett Wilson", s: "Ohio State", p: "WR", e: "2020s", r: 88 },
  { n: "Chris Olave", s: "Ohio State", p: "WR", e: "2020s", r: 87 },
  { n: "Ted Ginn Jr.", s: "Ohio State", p: "WR", e: "2000s", r: 85 },
  { n: "Joey Bosa", s: "Ohio State", p: "EDGE", e: "2010s", r: 92 },
  { n: "Nick Bosa", s: "Ohio State", p: "EDGE", e: "2010s", r: 93 },
  { n: "Chase Young", s: "Ohio State", p: "EDGE", e: "2010s", r: 93 },
  { n: "Cameron Heyward", s: "Ohio State", p: "DT", e: "2000s", r: 87 },
  { n: "A.J. Hawk", s: "Ohio State", p: "LB", e: "2000s", r: 88 },
  { n: "James Laurinaitis", s: "Ohio State", p: "LB", e: "2000s", r: 88 },
  { n: "Ryan Shazier", s: "Ohio State", p: "LB", e: "2010s", r: 87 },
  { n: "Marshon Lattimore", s: "Ohio State", p: "CB", e: "2010s", r: 87 },
  { n: "Denzel Ward", s: "Ohio State", p: "CB", e: "2010s", r: 86 },
  { n: "Jeff Okudah", s: "Ohio State", p: "CB", e: "2010s", r: 85 },
  { n: "Malik Hooker", s: "Ohio State", p: "S", e: "2010s", r: 85 },
  { n: "Mike Doss", s: "Ohio State", p: "S", e: "2000s", r: 84 },

  // ===== GEORGIA =====
  { n: "Aaron Murray", s: "Georgia", p: "QB", e: "2010s", r: 84 },
  { n: "Matthew Stafford", s: "Georgia", p: "QB", e: "2000s", r: 88 },
  { n: "Stetson Bennett", s: "Georgia", p: "QB", e: "2020s", r: 83 },
  { n: "Herschel Walker", s: "Georgia", p: "RB", e: "1980s", r: 98 },
  { n: "Nick Chubb", s: "Georgia", p: "RB", e: "2010s", r: 91 },
  { n: "Todd Gurley", s: "Georgia", p: "RB", e: "2010s", r: 90 },
  { n: "Knowshon Moreno", s: "Georgia", p: "RB", e: "2000s", r: 85 },
  { n: "A.J. Green", s: "Georgia", p: "WR", e: "2000s", r: 92 },
  { n: "Hines Ward", s: "Georgia", p: "WR", e: "1990s", r: 86 },
  { n: "George Pickens", s: "Georgia", p: "WR", e: "2020s", r: 84 },
  { n: "Brock Bowers", s: "Georgia", p: "TE", e: "2020s", r: 93 },
  { n: "David Pollack", s: "Georgia", p: "EDGE", e: "2000s", r: 90 },
  { n: "Jarvis Jones", s: "Georgia", p: "EDGE", e: "2010s", r: 88 },
  { n: "Jordan Davis", s: "Georgia", p: "DT", e: "2020s", r: 88 },
  { n: "Jalen Carter", s: "Georgia", p: "DT", e: "2020s", r: 90 },
  { n: "Geno Atkins", s: "Georgia", p: "DT", e: "2000s", r: 85 },
  { n: "Roquan Smith", s: "Georgia", p: "LB", e: "2010s", r: 90 },
  { n: "Thomas Davis", s: "Georgia", p: "LB", e: "2000s", r: 86 },
  { n: "Nakobe Dean", s: "Georgia", p: "LB", e: "2020s", r: 85 },
  { n: "Champ Bailey", s: "Georgia", p: "CB", e: "1990s", r: 93 },
  { n: "Eric Stokes", s: "Georgia", p: "CB", e: "2020s", r: 80 },

  // ===== USC =====
  { n: "Carson Palmer", s: "USC", p: "QB", e: "2000s", r: 89 },
  { n: "Matt Leinart", s: "USC", p: "QB", e: "2000s", r: 90 },
  { n: "Caleb Williams", s: "USC", p: "QB", e: "2020s", r: 91 },
  { n: "Sam Darnold", s: "USC", p: "QB", e: "2010s", r: 84 },
  { n: "Reggie Bush", s: "USC", p: "RB", e: "2000s", r: 96 },
  { n: "O.J. Simpson", s: "USC", p: "RB", e: "1960s", r: 97 },
  { n: "Marcus Allen", s: "USC", p: "RB", e: "1980s", r: 96 },
  { n: "Charles White", s: "USC", p: "RB", e: "1970s", r: 90 },
  { n: "Keyshawn Johnson", s: "USC", p: "WR", e: "1990s", r: 88 },
  { n: "Lynn Swann", s: "USC", p: "WR", e: "1970s", r: 87 },
  { n: "Robert Woods", s: "USC", p: "WR", e: "2010s", r: 84 },
  { n: "Drake London", s: "USC", p: "WR", e: "2020s", r: 85 },
  { n: "Junior Seau", s: "USC", p: "LB", e: "1980s", r: 95 },
  { n: "Brian Cushing", s: "USC", p: "LB", e: "2000s", r: 85 },
  { n: "Rey Maualuga", s: "USC", p: "LB", e: "2000s", r: 85 },
  { n: "Leonard Williams", s: "USC", p: "DT", e: "2010s", r: 87 },
  { n: "Troy Polamalu", s: "USC", p: "S", e: "2000s", r: 93 },
  { n: "Taylor Mays", s: "USC", p: "S", e: "2000s", r: 84 },
  { n: "Adoree' Jackson", s: "USC", p: "CB", e: "2010s", r: 85 },

  // ===== OKLAHOMA =====
  { n: "Baker Mayfield", s: "Oklahoma", p: "QB", e: "2010s", r: 92 },
  { n: "Kyler Murray", s: "Oklahoma", p: "QB", e: "2010s", r: 91 },
  { n: "Sam Bradford", s: "Oklahoma", p: "QB", e: "2000s", r: 89 },
  { n: "Jason White", s: "Oklahoma", p: "QB", e: "2000s", r: 84 },
  { n: "Jalen Hurts", s: "Oklahoma", p: "QB", e: "2010s", r: 88 },
  { n: "Adrian Peterson", s: "Oklahoma", p: "RB", e: "2000s", r: 96 },
  { n: "Billy Sims", s: "Oklahoma", p: "RB", e: "1970s", r: 93 },
  { n: "DeMarco Murray", s: "Oklahoma", p: "RB", e: "2000s", r: 85 },
  { n: "CeeDee Lamb", s: "Oklahoma", p: "WR", e: "2010s", r: 89 },
  { n: "Ryan Broyles", s: "Oklahoma", p: "WR", e: "2010s", r: 85 },
  { n: "Sterling Shepard", s: "Oklahoma", p: "WR", e: "2010s", r: 82 },
  { n: "Mark Andrews", s: "Oklahoma", p: "TE", e: "2010s", r: 87 },
  { n: "Jermaine Gresham", s: "Oklahoma", p: "TE", e: "2000s", r: 84 },
  { n: "Tommie Harris", s: "Oklahoma", p: "DT", e: "2000s", r: 88 },
  { n: "Gerald McCoy", s: "Oklahoma", p: "DT", e: "2000s", r: 88 },
  { n: "Brian Bosworth", s: "Oklahoma", p: "LB", e: "1980s", r: 89 },
  { n: "Teddy Lehman", s: "Oklahoma", p: "LB", e: "2000s", r: 83 },
  { n: "Roy Williams", s: "Oklahoma", p: "S", e: "2000s", r: 89 },
  { n: "Rickey Dixon", s: "Oklahoma", p: "S", e: "1980s", r: 84 },

  // ===== TEXAS =====
  { n: "Vince Young", s: "Texas", p: "QB", e: "2000s", r: 94 },
  { n: "Colt McCoy", s: "Texas", p: "QB", e: "2000s", r: 88 },
  { n: "Ricky Williams", s: "Texas", p: "RB", e: "1990s", r: 96 },
  { n: "Earl Campbell", s: "Texas", p: "RB", e: "1970s", r: 97 },
  { n: "Jamaal Charles", s: "Texas", p: "RB", e: "2000s", r: 86 },
  { n: "Bijan Robinson", s: "Texas", p: "RB", e: "2020s", r: 90 },
  { n: "Roy Williams", s: "Texas", p: "WR", e: "2000s", r: 86 },
  { n: "Xavier Worthy", s: "Texas", p: "WR", e: "2020s", r: 82 },
  { n: "Brian Orakpo", s: "Texas", p: "EDGE", e: "2000s", r: 88 },
  { n: "Casey Hampton", s: "Texas", p: "DT", e: "2000s", r: 86 },
  { n: "Derrick Johnson", s: "Texas", p: "LB", e: "2000s", r: 91 },
  { n: "Quentin Jammer", s: "Texas", p: "CB", e: "2000s", r: 84 },
  { n: "Aaron Ross", s: "Texas", p: "CB", e: "2000s", r: 82 },
  { n: "Michael Huff", s: "Texas", p: "S", e: "2000s", r: 86 },
  { n: "Earl Thomas", s: "Texas", p: "S", e: "2000s", r: 90 },

  // ===== MICHIGAN =====
  { n: "Tom Brady", s: "Michigan", p: "QB", e: "1990s", r: 88 },
  { n: "Chad Henne", s: "Michigan", p: "QB", e: "2000s", r: 82 },
  { n: "J.J. McCarthy", s: "Michigan", p: "QB", e: "2020s", r: 84 },
  { n: "Denard Robinson", s: "Michigan", p: "QB", e: "2010s", r: 85 },
  { n: "Mike Hart", s: "Michigan", p: "RB", e: "2000s", r: 85 },
  { n: "Blake Corum", s: "Michigan", p: "RB", e: "2020s", r: 85 },
  { n: "Anthony Thomas", s: "Michigan", p: "RB", e: "1990s", r: 82 },
  { n: "Braylon Edwards", s: "Michigan", p: "WR", e: "2000s", r: 88 },
  { n: "Anthony Carter", s: "Michigan", p: "WR", e: "1980s", r: 90 },
  { n: "Desmond Howard", s: "Michigan", p: "WR", e: "1990s", r: 90 },
  { n: "Jake Butt", s: "Michigan", p: "TE", e: "2010s", r: 82 },
  { n: "Aidan Hutchinson", s: "Michigan", p: "EDGE", e: "2020s", r: 91 },
  { n: "LaMarr Woodley", s: "Michigan", p: "EDGE", e: "2000s", r: 87 },
  { n: "Brandon Graham", s: "Michigan", p: "EDGE", e: "2000s", r: 86 },
  { n: "Mason Graham", s: "Michigan", p: "DT", e: "2020s", r: 86 },
  { n: "Devin Bush", s: "Michigan", p: "LB", e: "2010s", r: 84 },
  { n: "Charles Woodson", s: "Michigan", p: "CB", e: "1990s", r: 97 },
  { n: "Leon Hall", s: "Michigan", p: "CB", e: "2000s", r: 83 },

  // ===== NOTRE DAME =====
  { n: "Joe Montana", s: "Notre Dame", p: "QB", e: "1970s", r: 90 },
  { n: "Brady Quinn", s: "Notre Dame", p: "QB", e: "2000s", r: 84 },
  { n: "Jerome Bettis", s: "Notre Dame", p: "RB", e: "1990s", r: 88 },
  { n: "Autry Denson", s: "Notre Dame", p: "RB", e: "1990s", r: 80 },
  { n: "Tim Brown", s: "Notre Dame", p: "WR", e: "1980s", r: 92 },
  { n: "Michael Floyd", s: "Notre Dame", p: "WR", e: "2010s", r: 85 },
  { n: "Golden Tate", s: "Notre Dame", p: "WR", e: "2000s", r: 84 },
  { n: "Dave Casper", s: "Notre Dame", p: "TE", e: "1970s", r: 88 },
  { n: "Tyler Eifert", s: "Notre Dame", p: "TE", e: "2010s", r: 85 },
  { n: "Michael Mayer", s: "Notre Dame", p: "TE", e: "2020s", r: 84 },
  { n: "Justin Tuck", s: "Notre Dame", p: "EDGE", e: "2000s", r: 85 },
  { n: "Stephon Tuitt", s: "Notre Dame", p: "DT", e: "2010s", r: 83 },
  { n: "Manti Te'o", s: "Notre Dame", p: "LB", e: "2010s", r: 88 },
  { n: "Jaylon Smith", s: "Notre Dame", p: "LB", e: "2010s", r: 85 },
  { n: "Todd Lyght", s: "Notre Dame", p: "CB", e: "1990s", r: 84 },
  { n: "Kyle Hamilton", s: "Notre Dame", p: "S", e: "2020s", r: 90 },
  { n: "Harrison Smith", s: "Notre Dame", p: "S", e: "2000s", r: 84 },

  // ===== LSU =====
  { n: "Joe Burrow", s: "LSU", p: "QB", e: "2010s", r: 96 },
  { n: "JaMarcus Russell", s: "LSU", p: "QB", e: "2000s", r: 84 },
  { n: "Jayden Daniels", s: "LSU", p: "QB", e: "2020s", r: 91 },
  { n: "Leonard Fournette", s: "LSU", p: "RB", e: "2010s", r: 90 },
  { n: "Kevin Faulk", s: "LSU", p: "RB", e: "1990s", r: 86 },
  { n: "Justin Jefferson", s: "LSU", p: "WR", e: "2010s", r: 90 },
  { n: "Ja'Marr Chase", s: "LSU", p: "WR", e: "2010s", r: 93 },
  { n: "Odell Beckham Jr.", s: "LSU", p: "WR", e: "2010s", r: 89 },
  { n: "Jarvis Landry", s: "LSU", p: "WR", e: "2010s", r: 84 },
  { n: "Malik Nabers", s: "LSU", p: "WR", e: "2020s", r: 87 },
  { n: "Glenn Dorsey", s: "LSU", p: "DT", e: "2000s", r: 88 },
  { n: "Devin White", s: "LSU", p: "LB", e: "2010s", r: 87 },
  { n: "Patrick Peterson", s: "LSU", p: "CB", e: "2010s", r: 93 },
  { n: "Tyrann Mathieu", s: "LSU", p: "CB", e: "2010s", r: 89 },
  { n: "Derek Stingley Jr.", s: "LSU", p: "CB", e: "2020s", r: 88 },
  { n: "Morris Claiborne", s: "LSU", p: "CB", e: "2010s", r: 84 },
  { n: "LaRon Landry", s: "LSU", p: "S", e: "2000s", r: 85 },
  { n: "Grant Delpit", s: "LSU", p: "S", e: "2010s", r: 84 },

  // ===== FLORIDA =====
  { n: "Tim Tebow", s: "Florida", p: "QB", e: "2000s", r: 94 },
  { n: "Danny Wuerffel", s: "Florida", p: "QB", e: "1990s", r: 88 },
  { n: "Rex Grossman", s: "Florida", p: "QB", e: "2000s", r: 83 },
  { n: "Emmitt Smith", s: "Florida", p: "RB", e: "1980s", r: 93 },
  { n: "Fred Taylor", s: "Florida", p: "RB", e: "1990s", r: 85 },
  { n: "Percy Harvin", s: "Florida", p: "WR", e: "2000s", r: 88 },
  { n: "Jabar Gaffney", s: "Florida", p: "WR", e: "2000s", r: 83 },
  { n: "Aaron Hernandez", s: "Florida", p: "TE", e: "2000s", r: 85 },
  { n: "Jevon Kearse", s: "Florida", p: "EDGE", e: "1990s", r: 89 },
  { n: "Carlos Dunlap", s: "Florida", p: "EDGE", e: "2000s", r: 84 },
  { n: "Marcus Stroud", s: "Florida", p: "DT", e: "2000s", r: 84 },
  { n: "Brandon Spikes", s: "Florida", p: "LB", e: "2000s", r: 85 },
  { n: "Wilber Marshall", s: "Florida", p: "LB", e: "1980s", r: 90 },
  { n: "Joe Haden", s: "Florida", p: "CB", e: "2000s", r: 86 },
  { n: "Reggie Nelson", s: "Florida", p: "S", e: "2000s", r: 83 },
  { n: "Keanu Neal", s: "Florida", p: "S", e: "2010s", r: 80 },

  // ===== MIAMI =====
  { n: "Vinny Testaverde", s: "Miami", p: "QB", e: "1980s", r: 89 },
  { n: "Ken Dorsey", s: "Miami", p: "QB", e: "2000s", r: 84 },
  { n: "Bernie Kosar", s: "Miami", p: "QB", e: "1980s", r: 86 },
  { n: "Edgerrin James", s: "Miami", p: "RB", e: "1990s", r: 90 },
  { n: "Frank Gore", s: "Miami", p: "RB", e: "2000s", r: 87 },
  { n: "Clinton Portis", s: "Miami", p: "RB", e: "2000s", r: 85 },
  { n: "Michael Irvin", s: "Miami", p: "WR", e: "1980s", r: 92 },
  { n: "Andre Johnson", s: "Miami", p: "WR", e: "2000s", r: 91 },
  { n: "Reggie Wayne", s: "Miami", p: "WR", e: "1990s", r: 88 },
  { n: "Santana Moss", s: "Miami", p: "WR", e: "2000s", r: 85 },
  { n: "Jeremy Shockey", s: "Miami", p: "TE", e: "2000s", r: 86 },
  { n: "Kellen Winslow II", s: "Miami", p: "TE", e: "2000s", r: 85 },
  { n: "Greg Olsen", s: "Miami", p: "TE", e: "2000s", r: 85 },
  { n: "Warren Sapp", s: "Miami", p: "DT", e: "1990s", r: 95 },
  { n: "Vince Wilfork", s: "Miami", p: "DT", e: "2000s", r: 87 },
  { n: "Russell Maryland", s: "Miami", p: "DT", e: "1990s", r: 86 },
  { n: "Ray Lewis", s: "Miami", p: "LB", e: "1990s", r: 96 },
  { n: "Jonathan Vilma", s: "Miami", p: "LB", e: "2000s", r: 86 },
  { n: "Dan Morgan", s: "Miami", p: "LB", e: "2000s", r: 86 },
  { n: "Antrel Rolle", s: "Miami", p: "CB", e: "2000s", r: 84 },
  { n: "Ed Reed", s: "Miami", p: "S", e: "2000s", r: 95 },
  { n: "Sean Taylor", s: "Miami", p: "S", e: "2000s", r: 93 },

  // ===== FLORIDA STATE =====
  { n: "Charlie Ward", s: "Florida State", p: "QB", e: "1990s", r: 90 },
  { n: "Jameis Winston", s: "Florida State", p: "QB", e: "2010s", r: 88 },
  { n: "Chris Weinke", s: "Florida State", p: "QB", e: "2000s", r: 84 },
  { n: "Warrick Dunn", s: "Florida State", p: "RB", e: "1990s", r: 87 },
  { n: "Dalvin Cook", s: "Florida State", p: "RB", e: "2010s", r: 89 },
  { n: "Devonta Freeman", s: "Florida State", p: "RB", e: "2010s", r: 82 },
  { n: "Peter Warrick", s: "Florida State", p: "WR", e: "1990s", r: 88 },
  { n: "Anquan Boldin", s: "Florida State", p: "WR", e: "2000s", r: 85 },
  { n: "Fred Biletnikoff", s: "Florida State", p: "WR", e: "1960s", r: 88 },
  { n: "Peter Boulware", s: "Florida State", p: "EDGE", e: "1990s", r: 88 },
  { n: "Brian Burns", s: "Florida State", p: "EDGE", e: "2010s", r: 85 },
  { n: "Andre Wadsworth", s: "Florida State", p: "DT", e: "1990s", r: 85 },
  { n: "Derrick Brooks", s: "Florida State", p: "LB", e: "1990s", r: 93 },
  { n: "Ernie Sims", s: "Florida State", p: "LB", e: "2000s", r: 82 },
  { n: "Deion Sanders", s: "Florida State", p: "CB", e: "1980s", r: 98 },
  { n: "Jalen Ramsey", s: "Florida State", p: "CB", e: "2010s", r: 90 },
  { n: "Terrell Buckley", s: "Florida State", p: "CB", e: "1990s", r: 85 },
  { n: "Derwin James", s: "Florida State", p: "S", e: "2010s", r: 88 },

  // ===== NEBRASKA =====
  { n: "Tommie Frazier", s: "Nebraska", p: "QB", e: "1990s", r: 91 },
  { n: "Eric Crouch", s: "Nebraska", p: "QB", e: "2000s", r: 85 },
  { n: "Mike Rozier", s: "Nebraska", p: "RB", e: "1980s", r: 93 },
  { n: "Ahman Green", s: "Nebraska", p: "RB", e: "1990s", r: 86 },
  { n: "Roger Craig", s: "Nebraska", p: "RB", e: "1980s", r: 84 },
  { n: "Johnny Rodgers", s: "Nebraska", p: "WR", e: "1970s", r: 90 },
  { n: "Irving Fryar", s: "Nebraska", p: "WR", e: "1980s", r: 86 },
  { n: "Grant Wistrom", s: "Nebraska", p: "EDGE", e: "1990s", r: 86 },
  { n: "Ndamukong Suh", s: "Nebraska", p: "DT", e: "2000s", r: 95 },
  { n: "Trev Alberts", s: "Nebraska", p: "LB", e: "1990s", r: 85 },
  { n: "Lavonte David", s: "Nebraska", p: "LB", e: "2010s", r: 85 },
  { n: "Mike Brown", s: "Nebraska", p: "S", e: "1990s", r: 83 },

  // ===== PENN STATE =====
  { n: "Kerry Collins", s: "Penn State", p: "QB", e: "1990s", r: 85 },
  { n: "Trace McSorley", s: "Penn State", p: "QB", e: "2010s", r: 83 },
  { n: "Saquon Barkley", s: "Penn State", p: "RB", e: "2010s", r: 93 },
  { n: "Larry Johnson", s: "Penn State", p: "RB", e: "2000s", r: 88 },
  { n: "Ki-Jana Carter", s: "Penn State", p: "RB", e: "1990s", r: 87 },
  { n: "Curt Warner", s: "Penn State", p: "RB", e: "1980s", r: 85 },
  { n: "Bobby Engram", s: "Penn State", p: "WR", e: "1990s", r: 84 },
  { n: "Allen Robinson", s: "Penn State", p: "WR", e: "2010s", r: 84 },
  { n: "Chris Godwin", s: "Penn State", p: "WR", e: "2010s", r: 84 },
  { n: "Mike Gesicki", s: "Penn State", p: "TE", e: "2010s", r: 82 },
  { n: "Pat Freiermuth", s: "Penn State", p: "TE", e: "2020s", r: 82 },
  { n: "Micah Parsons", s: "Penn State", p: "LB", e: "2020s", r: 92 },
  { n: "LaVar Arrington", s: "Penn State", p: "LB", e: "1990s", r: 92 },
  { n: "Paul Posluszny", s: "Penn State", p: "LB", e: "2000s", r: 86 },
  { n: "Jack Ham", s: "Penn State", p: "LB", e: "1970s", r: 90 },
  { n: "Sean Lee", s: "Penn State", p: "LB", e: "2000s", r: 84 },
  { n: "Carl Nassib", s: "Penn State", p: "EDGE", e: "2010s", r: 82 },
  { n: "Joey Porter Jr.", s: "Penn State", p: "CB", e: "2020s", r: 82 },

  // ===== TENNESSEE =====
  { n: "Peyton Manning", s: "Tennessee", p: "QB", e: "1990s", r: 95 },
  { n: "Heath Shuler", s: "Tennessee", p: "QB", e: "1990s", r: 83 },
  { n: "Hendon Hooker", s: "Tennessee", p: "QB", e: "2020s", r: 84 },
  { n: "Jamal Lewis", s: "Tennessee", p: "RB", e: "1990s", r: 86 },
  { n: "Arian Foster", s: "Tennessee", p: "RB", e: "2000s", r: 83 },
  { n: "Alvin Kamara", s: "Tennessee", p: "RB", e: "2010s", r: 85 },
  { n: "Donte Stallworth", s: "Tennessee", p: "WR", e: "2000s", r: 82 },
  { n: "Cordarrelle Patterson", s: "Tennessee", p: "WR", e: "2010s", r: 82 },
  { n: "Jason Witten", s: "Tennessee", p: "TE", e: "2000s", r: 86 },
  { n: "Reggie White", s: "Tennessee", p: "EDGE", e: "1980s", r: 96 },
  { n: "Derek Barnett", s: "Tennessee", p: "EDGE", e: "2010s", r: 84 },
  { n: "John Henderson", s: "Tennessee", p: "DT", e: "2000s", r: 86 },
  { n: "Albert Haynesworth", s: "Tennessee", p: "DT", e: "2000s", r: 85 },
  { n: "Al Wilson", s: "Tennessee", p: "LB", e: "1990s", r: 85 },
  { n: "Eric Berry", s: "Tennessee", p: "S", e: "2000s", r: 91 },

  // ===== AUBURN =====
  { n: "Cam Newton", s: "Auburn", p: "QB", e: "2010s", r: 95 },
  { n: "Pat Sullivan", s: "Auburn", p: "QB", e: "1970s", r: 85 },
  { n: "Jason Campbell", s: "Auburn", p: "QB", e: "2000s", r: 82 },
  { n: "Bo Jackson", s: "Auburn", p: "RB", e: "1980s", r: 98 },
  { n: "Carnell Williams", s: "Auburn", p: "RB", e: "2000s", r: 86 },
  { n: "Ronnie Brown", s: "Auburn", p: "RB", e: "2000s", r: 84 },
  { n: "Tre Mason", s: "Auburn", p: "RB", e: "2010s", r: 82 },
  { n: "Nick Fairley", s: "Auburn", p: "DT", e: "2010s", r: 87 },
  { n: "Tracy Rocker", s: "Auburn", p: "DT", e: "1980s", r: 85 },
  { n: "Takeo Spikes", s: "Auburn", p: "LB", e: "1990s", r: 85 },
  { n: "Karlos Dansby", s: "Auburn", p: "LB", e: "2000s", r: 84 },
  { n: "Carlos Rogers", s: "Auburn", p: "CB", e: "2000s", r: 83 },
  { n: "Carlton Davis", s: "Auburn", p: "CB", e: "2010s", r: 80 },

  // ===== CLEMSON =====
  { n: "Deshaun Watson", s: "Clemson", p: "QB", e: "2010s", r: 93 },
  { n: "Trevor Lawrence", s: "Clemson", p: "QB", e: "2020s", r: 93 },
  { n: "Tajh Boyd", s: "Clemson", p: "QB", e: "2010s", r: 84 },
  { n: "C.J. Spiller", s: "Clemson", p: "RB", e: "2000s", r: 89 },
  { n: "Travis Etienne", s: "Clemson", p: "RB", e: "2010s", r: 89 },
  { n: "DeAndre Hopkins", s: "Clemson", p: "WR", e: "2010s", r: 89 },
  { n: "Sammy Watkins", s: "Clemson", p: "WR", e: "2010s", r: 88 },
  { n: "Tee Higgins", s: "Clemson", p: "WR", e: "2010s", r: 85 },
  { n: "Mike Williams", s: "Clemson", p: "WR", e: "2010s", r: 84 },
  { n: "Vic Beasley", s: "Clemson", p: "EDGE", e: "2010s", r: 86 },
  { n: "Clelin Ferrell", s: "Clemson", p: "EDGE", e: "2010s", r: 84 },
  { n: "Gaines Adams", s: "Clemson", p: "EDGE", e: "2000s", r: 84 },
  { n: "Christian Wilkins", s: "Clemson", p: "DT", e: "2010s", r: 86 },
  { n: "Dexter Lawrence", s: "Clemson", p: "DT", e: "2010s", r: 86 },
  { n: "Isaiah Simmons", s: "Clemson", p: "LB", e: "2010s", r: 88 },
  { n: "A.J. Terrell", s: "Clemson", p: "CB", e: "2010s", r: 82 },

  // ===== OREGON =====
  { n: "Marcus Mariota", s: "Oregon", p: "QB", e: "2010s", r: 92 },
  { n: "Justin Herbert", s: "Oregon", p: "QB", e: "2010s", r: 88 },
  { n: "Joey Harrington", s: "Oregon", p: "QB", e: "2000s", r: 84 },
  { n: "Bo Nix", s: "Oregon", p: "QB", e: "2020s", r: 85 },
  { n: "LaMichael James", s: "Oregon", p: "RB", e: "2010s", r: 87 },
  { n: "Jonathan Stewart", s: "Oregon", p: "RB", e: "2000s", r: 85 },
  { n: "Royce Freeman", s: "Oregon", p: "RB", e: "2010s", r: 84 },
  { n: "De'Anthony Thomas", s: "Oregon", p: "WR", e: "2010s", r: 82 },
  { n: "Kayvon Thibodeaux", s: "Oregon", p: "EDGE", e: "2020s", r: 88 },
  { n: "Haloti Ngata", s: "Oregon", p: "DT", e: "2000s", r: 90 },
  { n: "DeForest Buckner", s: "Oregon", p: "DT", e: "2010s", r: 86 },
  { n: "Arik Armstead", s: "Oregon", p: "DT", e: "2010s", r: 83 },
  { n: "Jevon Holland", s: "Oregon", p: "S", e: "2020s", r: 82 },
  { n: "T.J. Ward", s: "Oregon", p: "S", e: "2000s", r: 82 },

  // ===== NOTABLE OTHERS (one-offs / smaller programs) =====
  { n: "Randy Moss", s: "Marshall", p: "WR", e: "1990s", r: 96 },
  { n: "Chad Pennington", s: "Marshall", p: "QB", e: "1990s", r: 83 },
  { n: "Byron Leftwich", s: "Marshall", p: "QB", e: "2000s", r: 82 },
  { n: "Larry Fitzgerald", s: "Pittsburgh", p: "WR", e: "2000s", r: 95 },
  { n: "Tony Dorsett", s: "Pittsburgh", p: "RB", e: "1970s", r: 95 },
  { n: "Aaron Donald", s: "Pittsburgh", p: "DT", e: "2010s", r: 97 },
  { n: "Dan Marino", s: "Pittsburgh", p: "QB", e: "1980s", r: 90 },
  { n: "Darrelle Revis", s: "Pittsburgh", p: "CB", e: "2000s", r: 89 },
  { n: "Barry Sanders", s: "Oklahoma State", p: "RB", e: "1980s", r: 99 },
  { n: "Thurman Thomas", s: "Oklahoma State", p: "RB", e: "1980s", r: 90 },
  { n: "Justin Blackmon", s: "Oklahoma State", p: "WR", e: "2010s", r: 86 },
  { n: "Dez Bryant", s: "Oklahoma State", p: "WR", e: "2000s", r: 87 },
  { n: "Calvin Johnson", s: "Georgia Tech", p: "WR", e: "2000s", r: 95 },
  { n: "Demaryius Thomas", s: "Georgia Tech", p: "WR", e: "2000s", r: 83 },
  { n: "Michael Vick", s: "Virginia Tech", p: "QB", e: "2000s", r: 92 },
  { n: "Bruce Smith", s: "Virginia Tech", p: "EDGE", e: "1980s", r: 94 },
  { n: "DeAngelo Hall", s: "Virginia Tech", p: "CB", e: "2000s", r: 83 },
  { n: "Tremaine Edmunds", s: "Virginia Tech", p: "LB", e: "2010s", r: 84 },
  { n: "Andre Ware", s: "Houston", p: "QB", e: "1980s", r: 84 },
  { n: "Case Keenum", s: "Houston", p: "QB", e: "2010s", r: 83 },
  { n: "Ty Detmer", s: "BYU", p: "QB", e: "1990s", r: 87 },
  { n: "Steve Young", s: "BYU", p: "QB", e: "1980s", r: 90 },
  { n: "Jim McMahon", s: "BYU", p: "QB", e: "1980s", r: 84 },
  { n: "Luke Staley", s: "BYU", p: "RB", e: "2000s", r: 80 },
  { n: "Ashton Jeanty", s: "Boise State", p: "RB", e: "2020s", r: 91 },
  { n: "Doug Martin", s: "Boise State", p: "RB", e: "2010s", r: 82 },
  { n: "Kellen Moore", s: "Boise State", p: "QB", e: "2010s", r: 83 },
  { n: "Colt Brennan", s: "Hawaii", p: "QB", e: "2000s", r: 83 },
  { n: "Davante Adams", s: "Fresno State", p: "WR", e: "2010s", r: 87 },
  { n: "Derek Carr", s: "Fresno State", p: "QB", e: "2010s", r: 83 },
  { n: "Marshall Faulk", s: "San Diego State", p: "RB", e: "1990s", r: 93 },
  { n: "Brett Favre", s: "Southern Miss", p: "QB", e: "1990s", r: 86 },
  { n: "Jerry Rice", s: "Mississippi Valley State", p: "WR", e: "1980s", r: 95 },
  { n: "Walter Payton", s: "Jackson State", p: "RB", e: "1970s", r: 95 },
  { n: "Steve McNair", s: "Alcorn State", p: "QB", e: "1990s", r: 88 },
];
